# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 63ce16d44fb71cec5270292527e2f6c8d773b2a38cd9c4bee56288f3a1ac3e189608b21760a5284301580ef2b075771413470010993d70e36fc5f266da80c19d

test:
  secret_key_base: 6f53daaea34c6d0c3b7d91dcfab492b686b9c2b6f06e993b9cf586769a53d6faa86ddfa2f5f75b5bbdedc71493bc9e907bf1d3dc41fdfc7dc0a5488034a39f42

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
